# 1.1.1 Aggregated Transaction
## Data Extraction and Cleaning

In [1]:
import os
import json
import pandas as pd

path = r"D:/Viki/Guvi DS/Capstone Projects/PhonePe-Pulse-Project/pulse/data/aggregated/transaction/country/india/state"

data = []

# Looping through states, years, quarters, untill to JSON file which contains the required data
for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                quarter_num = int(file.split(".")[0])
                quarter = f"FY{quarter_num}"

                with open(file_path, 'r') as file:           # Loading JSON File
                    content = json.load(file)

                if 'data' in content and 'transactionData' in content['data']:

                    for item in content['data']['transactionData']:
                        category_name = item.get('name')

                        paymentInstruments = item.get('paymentInstruments', [])

                        if paymentInstruments:
                            transaction_count = paymentInstruments[0].get('count', 0)
                            transaction_amount = paymentInstruments[0].get('amount', 0)
                        else:
                            transaction_count = 0
                            transaction_amount = 0

                        
                        data.append({
                            "State": state,
                            "Year": int(year),
                            "Quarter_Num" : quarter_num,
                            "Quarter": f"FY{quarter_num}",            # Appending Each data
                            "Category_Name": category_name,
                            "Transaction_count": transaction_count,
                            "Transaction_amount": transaction_amount
                        })


df = pd.DataFrame(data)

print(df.head())            #To view the headings of the created Data Frame


df.to_csv("phonepe_transactions.csv", index=False)  

print("********** Data extraction completed and saved as CSV file **********")

                       State  Year  Quarter_Num Quarter  \
0  andaman-&-nicobar-islands  2018            1     FY1
1  andaman-&-nicobar-islands  2018            1     FY1
2  andaman-&-nicobar-islands  2018            1     FY1
3  andaman-&-nicobar-islands  2018            1     FY1
4  andaman-&-nicobar-islands  2018            1     FY1

              Category_Name  Transaction_count  Transaction_amount
0  Recharge & bill payments               4200        1.845307e+06
1     Peer-to-peer payments               1871        1.213866e+07
2         Merchant payments                298        4.525072e+05
3        Financial Services                 33        1.060142e+04
4                    Others                256        1.846899e+05
********** Data extraction completed and saved as CSV file **********

In [2]:
df

,State,Year,Quarter_Num,Quarter,Category_Name,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,FY1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,FY1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,FY1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,FY1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,FY1,Others,256,1.846899e+05
...,...,...,...,...,...,...,...
5029,west-bengal,2024,4,FY4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,FY4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,FY4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,FY4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,FY4,Others,421806,5.053641e+08

In [3]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\phonepe_transactions.csv")

print(df.head())

                       State  Year  Quarter_Num Quarter  \
0  andaman-&-nicobar-islands  2018            1     FY1
1  andaman-&-nicobar-islands  2018            1     FY1
2  andaman-&-nicobar-islands  2018            1     FY1
3  andaman-&-nicobar-islands  2018            1     FY1
4  andaman-&-nicobar-islands  2018            1     FY1

              Category_Name  Transaction_count  Transaction_amount
0  Recharge & bill payments               4200        1.845307e+06
1     Peer-to-peer payments               1871        1.213866e+07
2         Merchant payments                298        4.525072e+05
3        Financial Services                 33        1.060142e+04
4                    Others                256        1.846899e+05

In [4]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\phonepe_transactions.csv")

print(df.describe())

              Year  Quarter_Num  Transaction_count  Transaction_amount
count  5034.000000  5034.000000       5.034000e+03        5.034000e+03
mean   2021.002582     2.500795       4.673902e+07        6.863772e+10
std       1.999849     1.118145       1.690968e+08        2.685200e+11
min    2018.000000     1.000000       2.000000e+00        3.439721e+01
25%    2019.000000     2.000000       5.808950e+04        3.993888e+07
50%    2021.000000     3.000000       5.158310e+05        4.394139e+08
75%    2023.000000     4.000000       1.166629e+07        1.102822e+10
max    2024.000000     4.000000       2.393918e+09        3.095666e+12

In [5]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\phonepe_transactions.csv")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5034 non-null   object
 1   Year                5034 non-null   int64
 2   Quarter_Num         5034 non-null   int64
 3   Quarter             5034 non-null   object
 4   Category_Name       5034 non-null   object
 5   Transaction_count   5034 non-null   int64
 6   Transaction_amount  5034 non-null   float64
dtypes: float64(1), int64(3), object(3)
memory usage: 275.4+ KB
None

In [6]:
df.isnull().sum()

State                 0
Year                  0
Quarter_Num           0
Quarter               0
Category_Name         0
Transaction_count     0
Transaction_amount    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

              Year  Quarter_Num  Transaction_count  Transaction_amount
count  5034.000000  5034.000000       5.034000e+03        5.034000e+03
mean   2021.002582     2.500795       4.673902e+07        6.863772e+10
std       1.999849     1.118145       1.690968e+08        2.685200e+11
min    2018.000000     1.000000       2.000000e+00        3.439721e+01
25%    2019.000000     2.000000       5.808950e+04        3.993888e+07
50%    2021.000000     3.000000       5.158310e+05        4.394139e+08
75%    2023.000000     4.000000       1.166629e+07        1.102822e+10
max    2024.000000     4.000000       2.393918e+09        3.095666e+12

In [9]:
df["State"].unique()

array(['andaman-&-nicobar-islands', 'andhra-pradesh', 'arunachal-pradesh',
       'assam', 'bihar', 'chandigarh', 'chhattisgarh',
       'dadra-&-nagar-haveli-&-daman-&-diu', 'delhi', 'goa', 'gujarat',
       'haryana', 'himachal-pradesh', 'jammu-&-kashmir', 'jharkhand',
       'karnataka', 'kerala', 'ladakh', 'lakshadweep', 'madhya-pradesh',
       'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland',
       'odisha', 'puducherry', 'punjab', 'rajasthan', 'sikkim',
       'tamil-nadu', 'telangana', 'tripura', 'uttar-pradesh',
       'uttarakhand', 'west-bengal'], dtype=object)

In [ ]:
result = df.groupby("State")["Amount"].sum().sort_values(ascending=False).reset_index()

# Convert to Crores
result["Amount_in_Crore"] = result["Amount"] / 1e7

print(result.head(10))

            State        Amount  Amount_in_Crore
0       telangana  4.165596e+13     4.165596e+06
1       karnataka  4.067872e+13     4.067872e+06
2     maharashtra  4.037420e+13     4.037420e+06
3  andhra-pradesh  3.466908e+13     3.466908e+06
4   uttar-pradesh  2.688521e+13     2.688521e+06
5       rajasthan  2.634324e+13     2.634324e+06
6  madhya-pradesh  1.912528e+13     1.912528e+06
7           bihar  1.790135e+13     1.790135e+06
8     west-bengal  1.558416e+13     1.558416e+06
9          odisha  1.226398e+13     1.226398e+06

In [ ]:
pd.options.display.float_format = '{:.2f}'.format
print(result)

                                 State            Amount  Amount_in_Crore
0                            telangana 41655955630076.32       4165595.56
1                            karnataka 40678721773666.38       4067872.18
2                          maharashtra 40374195687971.67       4037419.57
3                       andhra-pradesh 34669080454846.84       3466908.05
4                        uttar-pradesh 26885212184899.86       2688521.22
5                            rajasthan 26343235566259.24       2634323.56
6                       madhya-pradesh 19125279433026.82       1912527.94
7                                bihar 17901349344779.72       1790134.93
8                          west-bengal 15584164309413.68       1558416.43
9                               odisha 12263982051532.62       1226398.21
10                          tamil-nadu 11936219022648.53       1193621.90
11                               delhi 11637520248963.95       1163752.02
12                             gujarat 10192905823125.37       1019290.58
13                             haryana  9645036562815.90        964503.66
14                           jharkhand  5906646115660.92        590664.61
15                        chhattisgarh  4890472317487.82        489047.23
16                               assam  3460792155997.89        346079.22
17                              kerala  3076269164129.14        307626.92
18                              punjab  2983077809927.29        298307.78
19                         uttarakhand  1916488572014.32        191648.86
20                     jammu-&-kashmir  1184683177572.73        118468.32
21                    himachal-pradesh   687537358746.40         68753.74
22                                 goa   511021161407.30         51102.12
23                          chandigarh   292906588372.69         29290.66
24                   arunachal-pradesh   274434950651.68         27443.50
25                          puducherry   237317074404.27         23731.71
26  dadra-&-nagar-haveli-&-daman-&-diu   201719857192.12         20171.99
27                             tripura   200583408419.46         20058.34
28                             manipur   186265635029.74         18626.56
29                           meghalaya   162543901207.48         16254.39
30                            nagaland   130358591755.70         13035.86
31                              sikkim   118945401940.85         11894.54
32                              ladakh    88994622100.10          8899.46
33           andaman-&-nicobar-islands    70667453146.60          7066.75
34                             mizoram    46102103410.33          4610.21
35                         lakshadweep     1609320784.78           160.93

In [ ]:
top10 = result.head(10)
top10

            State            Amount  Amount_in_Crore
0       telangana 41655955630076.32       4165595.56
1       karnataka 40678721773666.38       4067872.18
2     maharashtra 40374195687971.67       4037419.57
3  andhra-pradesh 34669080454846.84       3466908.05
4   uttar-pradesh 26885212184899.86       2688521.22
5       rajasthan 26343235566259.24       2634323.56
6  madhya-pradesh 19125279433026.82       1912527.94
7           bihar 17901349344779.72       1790134.93
8     west-bengal 15584164309413.68       1558416.43
9          odisha 12263982051532.62       1226398.21

## 1.1.2 Loading Data into Aggregated Transaction Table

In [ ]:
import pandas as pd
import mysql.connector

df = pd.read_csv("D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\Data\phonepe_transactions.csv")        #Reading CSV to to a Variable File

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepe_db"
)

cursor = connection.cursor()

                                                        #Convert dataframe to list of tuples
data = [tuple(row) for row in df.to_numpy()]

                                                        #Inserting data
cursor.executemany("""
INSERT INTO aggregated_transaction 
(State, Year, Quarter_Num, Quarter, Category_Name, Count, Amount)
VALUES (%s, %s, %s, %s, %s, %s, %s)
""", data)

connection.commit()

print("Data inserted successfully!")

connection.close()

# 1.2.1 Aggregated User
## Data Extraction and Cleaning

In [11]:
import os
import json
import pandas as pd

# 🔹 Path to aggregated user data
path = r"D:/Viki/Guvi DS/Capstone Projects/PhonePe-Pulse-Project/pulse/data/aggregated/user/country/india/state"

data = []

# 🔹 Looping  through each folder to get the required json files
for state in os.listdir(path):
    state_path = os.path.join(path, state)
    
    
    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)
        
        
        for file in os.listdir(year_path):
            
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)
                
                with open(file_path, "r") as f:
                    content = json.load(f)
                    
                    try:
                        # Extract user data
                        users = content["data"]["usersByDevice"]
                        
                        for row in users:
                            data.append({
                                "State": state,
                                "Year": int(year),
                                "Quarter_Num": int(file.strip(".json")),
                                "Quarter": "Q" + file.strip(".json"),
                                "Brand": row["brand"],
                                "Registered_users": row["count"],
                                "Device_share": row["percentage"]   # NOTE: No app opens in dataset → using percentage
                            })
                    
                    except:
                        # Some files may not have usersByDevice
                        continue

df = pd.DataFrame(data)

df.to_csv("aggregated_user.csv", index=False)

print("Aggregated User CSV created successfully!")
print(df.head())

Aggregated User CSV created successfully!
                       State  Year  Quarter_Num Quarter    Brand  \
0  andaman-&-nicobar-islands  2018            1      Q1   Xiaomi
1  andaman-&-nicobar-islands  2018            1      Q1  Samsung
2  andaman-&-nicobar-islands  2018            1      Q1     Vivo
3  andaman-&-nicobar-islands  2018            1      Q1     Oppo
4  andaman-&-nicobar-islands  2018            1      Q1  OnePlus

   Registered_users  Device_share
0              1665      0.247033
1              1445      0.214392
2               982      0.145697
3               501      0.074332
4               332      0.049258

In [12]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\aggregated_user.csv")

print(df.head())

                       State  Year  Quarter_Num Quarter    Brand  \
0  andaman-&-nicobar-islands  2018            1      Q1   Xiaomi
1  andaman-&-nicobar-islands  2018            1      Q1  Samsung
2  andaman-&-nicobar-islands  2018            1      Q1     Vivo
3  andaman-&-nicobar-islands  2018            1      Q1     Oppo
4  andaman-&-nicobar-islands  2018            1      Q1  OnePlus

   Registered_users  Device_share
0              1665      0.247033
1              1445      0.214392
2               982      0.145697
3               501      0.074332
4               332      0.049258

In [13]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\aggregated_user.csv")

print(df.describe())

              Year  Quarter_Num  Registered_users  Device_share
count  6732.000000  6732.000000      6.732000e+03   6732.000000
mean   2019.647059     2.411765      5.140115e+05      0.090909
std       1.233984     1.140715      1.081772e+06      0.083401
min    2018.000000     1.000000      1.000000e+01      0.005158
25%    2019.000000     1.000000      9.354000e+03      0.020513
50%    2020.000000     2.000000      8.472250e+04      0.057718
75%    2021.000000     3.000000      4.555808e+05      0.146007
max    2022.000000     4.000000      1.134094e+07      0.478367

In [14]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\aggregated_user.csv")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6732 entries, 0 to 6731
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             6732 non-null   object
 1   Year              6732 non-null   int64
 2   Quarter_Num       6732 non-null   int64
 3   Quarter           6732 non-null   object
 4   Brand             6732 non-null   object
 5   Registered_users  6732 non-null   int64
 6   Device_share      6732 non-null   float64
dtypes: float64(1), int64(3), object(3)
memory usage: 368.3+ KB
None

In [15]:
df.isnull().sum()

State               0
Year                0
Quarter_Num         0
Quarter             0
Brand               0
Registered_users    0
Device_share        0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["State"].unique()

array(['andaman-&-nicobar-islands', 'andhra-pradesh', 'arunachal-pradesh',
       'assam', 'bihar', 'chandigarh', 'chhattisgarh',
       'dadra-&-nagar-haveli-&-daman-&-diu', 'delhi', 'goa', 'gujarat',
       'haryana', 'himachal-pradesh', 'jammu-&-kashmir', 'jharkhand',
       'karnataka', 'kerala', 'ladakh', 'lakshadweep', 'madhya-pradesh',
       'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland',
       'odisha', 'puducherry', 'punjab', 'rajasthan', 'sikkim',
       'tamil-nadu', 'telangana', 'tripura', 'uttar-pradesh',
       'uttarakhand', 'west-bengal'], dtype=object)

In [21]:
df["Brand"].unique()

array(['Xiaomi', 'Samsung', 'Vivo', 'Oppo', 'OnePlus', 'Realme', 'Apple',
       'Motorola', 'Lenovo', 'Huawei', 'Others', 'Tecno', 'Gionee',
       'Infinix', 'Asus', 'Micromax', 'HMD Global', 'Lava', 'COOLPAD',
       'Lyf'], dtype=object)

## 1.2.2 Loading Data into Aggregaed User Table

In [1]:
import mysql.connector
import pandas as pd

df = pd.read_csv("aggregated_user.csv")

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepe_db"
)

cursor = connection.cursor()

                                            # Insert Query to insert data from csv file to aggregated_user table
query = """
INSERT INTO aggregated_user (
    State, 
    Year, 
    Quarter_Num, 
    Quarter,
    Brand, 
    Registered_users, 
    Device_share
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

data = [tuple(row) for row in df.values]

cursor.executemany(query, data)
connection.commit()

#------------------------------------------------------------------------------------------------------------------------

                                                    # Data Validation and Display

cursor.execute("SELECT COUNT(*) FROM aggregated_user")
total_rows = cursor.fetchone()[0]

print(f"\nTotal Rows in aggregated_user: {total_rows}")


cursor.execute("""
SELECT 
        State, 
        Year, 
        Quarter, 
        Brand, 
        Registered_users, 
        Device_share
FROM aggregated_user
LIMIT 5
""")

rows = cursor.fetchall()

print("\nSample Data:\n")
for r in rows:
    print(r)

connection.close()

Total Rows in aggregated_user: 6732

Sample Data:

('andaman-&-nicobar-islands', 2018, 'Q1', 'Xiaomi', 1665, 0.2470326409495549)
('andaman-&-nicobar-islands', 2018, 'Q1', 'Samsung', 1445, 0.2143916913946587)
('andaman-&-nicobar-islands', 2018, 'Q1', 'Vivo', 982, 0.1456973293768546)
('andaman-&-nicobar-islands', 2018, 'Q1', 'Oppo', 501, 0.0743323442136498)
('andaman-&-nicobar-islands', 2018, 'Q1', 'OnePlus', 332, 0.0492581602373887)

# 1.3.1 Aggregated insurance
## Data Extraction and Cleaning

In [2]:
import os
import json
import pandas as pd

# Set your correct base path
path = r"D:/Viki/Guvi DS/Capstone Projects/PhonePe-Pulse-Project/pulse/data/aggregated/insurance/country/india/state"

data = []

# Loop through states
for state in os.listdir(path):
    state_path = os.path.join(path, state)

    # Loop through years
    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        # Loop through quarters
        for quarter_file in os.listdir(year_path):
            file_path = os.path.join(year_path, quarter_file)

            with open(file_path, "r") as file:
                content = json.load(file)

                # Extracting data from JSON files and appending to the list and saving it as a CSV file
                try:
                    for item in content["data"]["transactionData"]:
                        name = item["name"]

                        for payment in item["paymentInstruments"]:
                            insurance_count = payment["count"]
                            insurance_amount = payment["amount"]

                            data.append({
                                "State": state,
                                "Year": int(year),
                                "Quarter": int(quarter_file.strip(".json")),
                                "Insurance_Type": name,
                                "Insurance_Count": insurance_count,
                                "Insurance_Amount": insurance_amount
                            })

                except:
                    pass  

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("aggregated_insurance.csv", index=False)

print("✅ Aggregated Insurance CSV created successfully!")
print(df.head())

✅ Aggregated Insurance CSV created successfully!
                       State  Year  Quarter Insurance_Type  Insurance_Count  \
0  andaman-&-nicobar-islands  2020        2      Insurance                6
1  andaman-&-nicobar-islands  2020        3      Insurance               41
2  andaman-&-nicobar-islands  2020        4      Insurance              124
3  andaman-&-nicobar-islands  2021        1      Insurance              225
4  andaman-&-nicobar-islands  2021        2      Insurance              137

   Insurance_Amount
0            1360.0
1           15380.0
2          157975.0
3          244266.0
4          181504.0

In [3]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\aggregated_insurance.csv")

print(df.head())

                       State  Year  Quarter Insurance_Type  Insurance_Count  \
0  andaman-&-nicobar-islands  2020        2      Insurance                6
1  andaman-&-nicobar-islands  2020        3      Insurance               41
2  andaman-&-nicobar-islands  2020        4      Insurance              124
3  andaman-&-nicobar-islands  2021        1      Insurance              225
4  andaman-&-nicobar-islands  2021        2      Insurance              137

   Insurance_Amount
0            1360.0
1           15380.0
2          157975.0
3          244266.0
4          181504.0

In [4]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\aggregated_insurance.csv")

print(df.describe())

              Year     Quarter  Insurance_Count  Insurance_Amount
count   682.000000  682.000000       682.000000      6.820000e+02
mean   2022.111437    2.577713     21283.998534      2.934836e+07
std       1.370730    1.092211     31503.745791      4.763085e+07
min    2020.000000    1.000000         4.000000      1.199000e+03
25%    2021.000000    2.000000       607.750000      8.211475e+05
50%    2022.000000    3.000000      6679.500000      6.675645e+06
75%    2023.000000    4.000000     29790.500000      3.730685e+07
max    2024.000000    4.000000    183532.000000      3.058618e+08

In [5]:
import pandas as pd

df = pd.read_csv(r"D:\Viki\Guvi DS\Capstone Projects\PhonePe-Pulse-Project\src\aggregated_insurance.csv")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             682 non-null    object
 1   Year              682 non-null    int64
 2   Quarter           682 non-null    int64
 3   Insurance_Type    682 non-null    object
 4   Insurance_Count   682 non-null    int64
 5   Insurance_Amount  682 non-null    float64
dtypes: float64(1), int64(3), object(2)
memory usage: 32.1+ KB
None

In [6]:
df.isnull().sum()

State               0
Year                0
Quarter             0
Insurance_Type      0
Insurance_Count     0
Insurance_Amount    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

## 1.3.2 Data Insertion into Aggregated Insurance Table

In [8]:
import mysql.connector
import pandas as pd

df = pd.read_csv("aggregated_insurance.csv")

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepe_db"
)

cursor = connection.cursor()

                                # Insert Query to insert data from csv file to aggregated_insurance table
insert_query = """
INSERT INTO aggregated_insurance (
    State, 
    Year, 
    Quarter, 
    Insurance_Type, 
    Insurance_count, 
    Insurance_amount
)
VALUES (%s, %s, %s, %s, %s, %s)
"""

data = list(df.itertuples(index=False, name=None))

print("📊 Total rows to insert:", len(data))

# Step 5: Insert Data
cursor.executemany(insert_query, data)
connection.commit()

print("✅ Data inserted successfully!")

# --------------------------------------------------------------------------------------------------------------------
# Step 6: Display Table Structure
print("\n📌 Table Structure:")
cursor.execute("DESCRIBE aggregated_insurance")
for row in cursor.fetchall():
    print(row)


# --------------------------------------------------------------------------------------------------------------------
# Step 8: Display Sample Data
print("\n📌 Sample Data:")
cursor.execute("SELECT * FROM aggregated_insurance LIMIT 10")
rows = cursor.fetchall()

for row in rows:
    print(row)

cursor.close()
connection.close()

📊 Total rows to insert: 682
✅ Data inserted successfully!

📌 Table Structure:
('State', 'varchar(100)', 'YES', '', None, '')
('Year', 'int', 'YES', '', None, '')
('Quarter', 'int', 'YES', '', None, '')
('Insurance_Type', 'varchar(100)', 'YES', '', None, '')
('Insurance_count', 'bigint', 'YES', '', None, '')
('Insurance_amount', 'double', 'YES', '', None, '')

📌 Sample Data:
('andaman-&-nicobar-islands', 2020, 2, 'Insurance', 6, 1360.0)
('andaman-&-nicobar-islands', 2020, 3, 'Insurance', 41, 15380.0)
('andaman-&-nicobar-islands', 2020, 4, 'Insurance', 124, 157975.0)
('andaman-&-nicobar-islands', 2021, 1, 'Insurance', 225, 244266.0)
('andaman-&-nicobar-islands', 2021, 2, 'Insurance', 137, 181504.0)
('andaman-&-nicobar-islands', 2021, 3, 'Insurance', 230, 305235.0)
('andaman-&-nicobar-islands', 2021, 4, 'Insurance', 757, 1056380.0)
('andaman-&-nicobar-islands', 2022, 1, 'Insurance', 768, 1131287.0)
('andaman-&-nicobar-islands', 2022, 2, 'Insurance', 501, 779740.0)
('andaman-&-nicobar-islands', 2022, 3, 'Insurance', 643, 902466.0)

# 2.1.1 Map User
## Data Extraction and Cleaning

In [9]:
import os
import json
import pandas as pd

path = r"D:/Viki/Guvi DS/Capstone Projects/PhonePe-Pulse-Project/pulse/data/map/user/hover/country/india/state"

data = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for quarter_file in os.listdir(year_path):
            file_path = os.path.join(year_path, quarter_file)

            with open(file_path, "r") as file:
                content = json.load(file)

                try:
                    users = content["data"]["hoverData"]

                    for district, details in users.items():
                        data.append({
                            "State": state,
                            "Year": int(year),
                            "Quarter": int(quarter_file.strip(".json")),
                            "District": district,
                            "Registered_Users": details["registeredUsers"],
                            "App_Opens": details["appOpens"]
                        })

                except:
                    pass

# Convert to DataFrame
df = pd.DataFrame(data)

df.to_csv("map_user.csv", index=False)

print("CSV file 'map_user.csv' created successfully!")
#----------------------------------------------------------------------------------------------------------------------

                                                # Display extracted data

print("Extracted Data Preview:")
print(df.head())
print("\nTotal Rows:", df.shape[0])

CSV file 'map_user.csv' created successfully!
Extracted Data Preview:
                       State  Year  Quarter  \
0  andaman-&-nicobar-islands  2018        1
1  andaman-&-nicobar-islands  2018        1
2  andaman-&-nicobar-islands  2018        1
3  andaman-&-nicobar-islands  2018        2
4  andaman-&-nicobar-islands  2018        2

                            District  Registered_Users  App_Opens
0  north and middle andaman district               632          0
1             south andaman district              5846          0
2                  nicobars district               262          0
3  north and middle andaman district               911          0
4             south andaman district              8143          0

Total Rows: 20608

## 2.1.2 Data Insertion into Map User Table

In [2]:
import mysql.connector 
import pandas as pd

df = pd.read_csv("map_user.csv")


connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepe_db"
)

cursor = connection.cursor()

insert_query = """
INSERT INTO map_user (
    State,
    Year,
    Quarter,
    District,
    Registered_Users, 
    App_Opens
)
VALUES (%s, %s, %s, %s, %s, %s)
"""

data = list(df.itertuples(index=False, name=None))

cursor.executemany(insert_query, data)
connection.commit()

print("Data inserted into map_user successfully!")

# ---------------------------------------------------------------------------------------------------------------------
                                                # Display total rows

print("\nTotal Rows in Table:")
cursor.execute("SELECT COUNT(*) FROM map_user")
print(cursor.fetchone())

print("\nSample Data:")
cursor.execute("SELECT * FROM map_user LIMIT 10")
for row in cursor.fetchall():
    print(row)

cursor.close()
connection.close()

Data inserted into map_user successfully!

Total Rows in Table:
(20608,)

Sample Data:
('andaman-&-nicobar-islands', 2018, 1, 'north and middle andaman district', 632, 0)
('andaman-&-nicobar-islands', 2018, 1, 'south andaman district', 5846, 0)
('andaman-&-nicobar-islands', 2018, 1, 'nicobars district', 262, 0)
('andaman-&-nicobar-islands', 2018, 2, 'north and middle andaman district', 911, 0)
('andaman-&-nicobar-islands', 2018, 2, 'south andaman district', 8143, 0)
('andaman-&-nicobar-islands', 2018, 2, 'nicobars district', 351, 0)
('andaman-&-nicobar-islands', 2018, 3, 'north and middle andaman district', 1208, 0)
('andaman-&-nicobar-islands', 2018, 3, 'south andaman district', 10474, 0)
('andaman-&-nicobar-islands', 2018, 3, 'nicobars district', 467, 0)
('andaman-&-nicobar-islands', 2018, 4, 'north and middle andaman district', 1553, 0)

# 2.2.1 Map_map (Map Transaction)
## Data Extraction and Cleaning

In [4]:
import os
import json
import pandas as pd

path = r"D:/Viki/Guvi DS/Capstone Projects/PhonePe-Pulse-Project/pulse/data/map/transaction/hover/country/india/state"

data = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for quarter_file in os.listdir(year_path):
            file_path = os.path.join(year_path, quarter_file)

            with open(file_path, "r") as file:
                content = json.load(file)

                try:
                    districts = content["data"]["hoverDataList"]

                    for item in districts:
                        data.append({
                            "State": state,
                            "Year": int(year),
                            "Quarter": int(quarter_file.strip(".json")),
                            "District": item["name"],
                            "Transaction_Count": item["metric"][0]["count"],
                            "Transaction_Amount": item["metric"][0]["amount"]
                        })

                except:
                    pass

# Convert to DataFrame
df = pd.DataFrame(data)

# Display
print("Extracted Data:")
print(df.head())
print("Total Rows:", df.shape[0])

# Save CSV
df.to_csv("map_map.csv", index=False)

print("CSV 'map_map.csv' created!")

Extracted Data:
                       State  Year  Quarter  \
0  andaman-&-nicobar-islands  2018        1
1  andaman-&-nicobar-islands  2018        1
2  andaman-&-nicobar-islands  2018        1
3  andaman-&-nicobar-islands  2018        2
4  andaman-&-nicobar-islands  2018        2

                            District  Transaction_Count  Transaction_Amount
0  north and middle andaman district                442        9.316631e+05
1             south andaman district               5688        1.256025e+07
2                  nicobars district                528        1.139849e+06
3  north and middle andaman district                825        1.317863e+06
4             south andaman district               9395        2.394824e+07
Total Rows: 20604
CSV 'map_map.csv' created!

In [5]:
import mysql.connector 
import pandas as pd

df = pd.read_csv("map_map.csv")


connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepe_db"
)

cursor = connection.cursor()

insert_query = """
INSERT INTO map_map (
    State, 
    Year, 
    Quarter, 
    District, 
    Transaction_Count, 
    Transaction_Amount
)
VALUES (%s, %s, %s, %s, %s, %s)
"""

data = list(df.itertuples(index=False, name=None))

cursor.executemany(insert_query, data)
connection.commit()

print("Data inserted into map_map!")

# --------------------------------------------------

                                            # Data Display and Validation

print("\nTotal Rows:")
cursor.execute("SELECT COUNT(*) FROM map_map")
print(cursor.fetchone())


print("\nSample Data:")
cursor.execute("SELECT * FROM map_map LIMIT 10")
for row in cursor.fetchall():
    print(row)

cursor.close()
connection.close()

Data inserted into map_map!

Total Rows:
(20604,)

Sample Data:
('andaman-&-nicobar-islands', 2018, 1, 'north and middle andaman district', 442, 931663.0770939871)
('andaman-&-nicobar-islands', 2018, 1, 'south andaman district', 5688, 12560249.34366581)
('andaman-&-nicobar-islands', 2018, 1, 'nicobars district', 528, 1139848.801225994)
('andaman-&-nicobar-islands', 2018, 2, 'north and middle andaman district', 825, 1317863.0834906558)
('andaman-&-nicobar-islands', 2018, 2, 'south andaman district', 9395, 23948235.51634325)
('andaman-&-nicobar-islands', 2018, 2, 'nicobars district', 1120, 3072436.9081196385)
('andaman-&-nicobar-islands', 2018, 3, 'north and middle andaman district', 1283, 4901529.518499676)
('andaman-&-nicobar-islands', 2018, 3, 'south andaman district', 13511, 44268112.46425246)
('andaman-&-nicobar-islands', 2018, 3, 'nicobars district', 1471, 6387829.151558982)
('andaman-&-nicobar-islands', 2018, 4, 'north and middle andaman district', 2137, 7955635.917688001)

# 2.3.1 Map Insurance
## Data Extraction and Cleaning

In [6]:
import os
import json
import pandas as pd

path = r"D:/Viki/Guvi DS/Capstone Projects/PhonePe-Pulse-Project/pulse/data/map/insurance/hover/country/india/state"

data = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for quarter_file in os.listdir(year_path):
            file_path = os.path.join(year_path, quarter_file)

            with open(file_path, "r") as file:
                content = json.load(file)

                try:
                    districts = content["data"]["hoverDataList"]

                    for item in districts:
                        data.append({
                            "State": state,
                            "Year": int(year),
                            "Quarter": int(quarter_file.strip(".json")),
                            "District": item["name"],
                            "Insurance_Count": item["metric"][0]["count"],
                            "Insurance_Amount": item["metric"][0]["amount"]
                        })

                except:
                    pass

df = pd.DataFrame(data)

#--------------------------------------------------------------------------------------------------------------------

                                            # Display extracted data

print("Extracted Data:")
print(df.head())
print("Total Rows:", df.shape[0])

# Save CSV
df.to_csv("map_insurance.csv", index=False)

print("CSV 'map_insurance.csv' created successfully!")

Extracted Data:
                       State  Year  Quarter  \
0  andaman-&-nicobar-islands  2020        2
1  andaman-&-nicobar-islands  2020        2
2  andaman-&-nicobar-islands  2020        3
3  andaman-&-nicobar-islands  2020        3
4  andaman-&-nicobar-islands  2020        3

                            District  Insurance_Count  Insurance_Amount
0             south andaman district                3             795.0
1                  nicobars district                3             565.0
2  north and middle andaman district                1             281.0
3             south andaman district               35           13651.0
4                  nicobars district                5            1448.0
Total Rows: 13876
CSV 'map_insurance.csv' created successfully!

# 2.3.2 Data Insertion into Map_Insurance Table

In [8]:
import mysql.connector 
import pandas as pd

df = pd.read_csv("map_insurance.csv")


connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepe_db"
)

cursor = connection.cursor()

insert_query = """
INSERT INTO map_insurance (
    State, 
    Year, 
    Quarter, 
    District, 
    Insurance_Count, 
    Insurance_Amount
)
VALUES (%s, %s, %s, %s, %s, %s)
"""

data = list(df.itertuples(index=False, name=None))

cursor.executemany(insert_query, data)
connection.commit()

print("Data inserted into map_insurance!")

# -----------------------------------------------------------------------------------------------------------------

                                                # Data Display and Validation

print("\nTotal Rows:")
cursor.execute("SELECT COUNT(*) FROM map_insurance")
print(cursor.fetchone())


print("\nSample Data:")
cursor.execute("SELECT * FROM map_insurance LIMIT 10")
for row in cursor.fetchall():
    print(row)

cursor.close()
connection.close()

Data inserted into map_insurance!

Total Rows:
(13876,)

Sample Data:
('andaman-&-nicobar-islands', 2020, 2, 'south andaman district', 3, 795.0)
('andaman-&-nicobar-islands', 2020, 2, 'nicobars district', 3, 565.0)
('andaman-&-nicobar-islands', 2020, 3, 'north and middle andaman district', 1, 281.0)
('andaman-&-nicobar-islands', 2020, 3, 'south andaman district', 35, 13651.0)
('andaman-&-nicobar-islands', 2020, 3, 'nicobars district', 5, 1448.0)
('andaman-&-nicobar-islands', 2020, 4, 'north and middle andaman district', 13, 17734.0)
('andaman-&-nicobar-islands', 2020, 4, 'south andaman district', 109, 137494.0)
('andaman-&-nicobar-islands', 2020, 4, 'nicobars district', 2, 2747.0)
('andaman-&-nicobar-islands', 2021, 1, 'north and middle andaman district', 48, 63978.0)
('andaman-&-nicobar-islands', 2021, 1, 'south andaman district', 164, 167044.0)

# 3.1.1 Top User
## DataCleaning and Extraction

In [9]:
import os
import json
import pandas as pd

path = r"D:/Viki/Guvi DS/Capstone Projects/PhonePe-Pulse-Project/pulse/data/top/user/country/india/state"

data = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for quarter_file in os.listdir(year_path):
            file_path = os.path.join(year_path, quarter_file)

            with open(file_path, "r") as file:
                content = json.load(file)

                try:
                    districts = content["data"]["districts"]

                    for item in districts:
                        data.append({
                            "State": state,
                            "Year": int(year),
                            "Quarter": int(quarter_file.strip(".json")),
                            "District": item["name"],
                            "Registered_Users": item["registeredUsers"]
                        })

                except:
                    pass

df = pd.DataFrame(data)

#------------------------------------------------------------------------------------------------------------------------

print("Extracted Data:")
print(df.head())
print("Total Rows:", df.shape[0])


df.to_csv("top_user.csv", index=False)

print("CSV 'top_user.csv' created!")

Extracted Data:
                       State  Year  Quarter                  District  \
0  andaman-&-nicobar-islands  2018        1             south andaman
1  andaman-&-nicobar-islands  2018        1  north and middle andaman
2  andaman-&-nicobar-islands  2018        1                  nicobars
3  andaman-&-nicobar-islands  2018        2             south andaman
4  andaman-&-nicobar-islands  2018        2  north and middle andaman

   Registered_Users
0              5846
1               632
2               262
3              8143
4               911
Total Rows: 8296
CSV 'top_user.csv' created!

## 3.1.2 Data Insertion into Top User table

In [14]:
import mysql.connector 
import pandas as pd

df = pd.read_csv("top_user.csv")


connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678",
    database="phonepe_db"
)

cursor = connection.cursor()

insert_query = """
INSERT INTO top_user (
    State, 
    Year, 
    Quarter, 
    District, 
    Registered_Users
)
VALUES (%s, %s, %s, %s, %s)
"""

data = list(df.itertuples(index=False, name=None))

cursor.executemany(insert_query, data)
connection.commit()

print("Data inserted into top_user")

#-----------------------------------------------------------------------------------------------------------------------

cursor.execute("SELECT COUNT(*) FROM top_user")
print(cursor.fetchone())

cursor.execute("SELECT * FROM top_user LIMIT 10")
for row in cursor.fetchall():
    print(row)

cursor.close()
connection.close()

Data inserted into top_user
(8296,)
('andaman-&-nicobar-islands', 2018, 1, 'south andaman', 5846)
('andaman-&-nicobar-islands', 2018, 1, 'north and middle andaman', 632)
('andaman-&-nicobar-islands', 2018, 1, 'nicobars', 262)
('andaman-&-nicobar-islands', 2018, 2, 'south andaman', 8143)
('andaman-&-nicobar-islands', 2018, 2, 'north and middle andaman', 911)
('andaman-&-nicobar-islands', 2018, 2, 'nicobars', 351)
('andaman-&-nicobar-islands', 2018, 3, 'south andaman', 10474)
('andaman-&-nicobar-islands', 2018, 3, 'north and middle andaman', 1208)
('andaman-&-nicobar-islands', 2018, 3, 'nicobars', 467)
('andaman-&-nicobar-islands', 2018, 4, 'south andaman', 13133)